# Generated by Django 3.2 on 2021-10-15 18:34

from django.db import migrations, models
import user.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Username')),
                ('cover', models.ImageField(blank=True, max_length=128, null=True, upload_to=user.models.user.get_file_path, verbose_name='Cover')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('main_image', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Main Image')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admin')),
                ('description', models.TextField(verbose_name='Description')),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='Total Follower')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Total Following')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='Total post')),
                ('follow', models.ManyToManyField(to='user.User', verbose_name='Follow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
