# Generated by Django 3.2 on 2022-01-14 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models.profile_image


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211023_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='type',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('FORGET', 'FORGET')], max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Activation Code'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile_image.get_file_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
