# Generated by Django 3.2 on 2021-10-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models.post


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('file', models.ImageField(blank=True, max_length=128, null=True, upload_to=post.models.post.get_file_path, verbose_name='Media')),
                ('reshare_count', models.PositiveIntegerField(default=0, verbose_name='Total Reshare')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Total Comment')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Total Like')),
                ('feed', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Feed')),
                ('like', models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='Like')),
                ('reshare', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reshares', to='post.post', verbose_name='Feed')),
                ('tag', models.ManyToManyField(to='tag.Tag', verbose_name='Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
